version: '2'

services:
  nginx:
    image: nginx:latest
    network_mode: "host"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro

  haproxy:
    image: 'dockercloud/haproxy:latest'
    links:
      - website
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:80"
      - "1936:1936"
    environment:
      - "STATUS_AUTH=auth:auth"
      - "STATUS_PORT=1936"

  website:
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
#    volumes:
#      - /your/production/config:/webapp-sample/instance:ro
    expose:
      - "8000"
    command: gunicorn -c file:config/gunicorn.py "webapp-sample.app:create_app()"
